### ISSUE TITLE
Music bot

### ISSUE THREAD

**Issue by FajsiEx** [FajsiEx/tea-bot#46]
Now that I know ffmpeg codec can be accessed via imports, the music bot framework will be a piece of cake ;). Should find hosting that supports ffmpeg codec install bc bluemix doesn't.
Hype.

**Comment by CodyM4V3R1CK** [comment]
OwO

**Comment by FajsiEx** [comment]
Been a secret for a long time but I have the code ready ;)

**Comment by FajsiEx** [comment]
Making progress...

**Comment by FajsiEx** [comment]
Done !stop !queue/mq/rada !skip commands. Endgame

**Comment by FajsiEx** [comment]
Tea-bot should now have all the useful functionality of fredboat when it comes to music...

**Comment by CodyM4V3R1CK** [comment]
!gj

**Comment by FajsiEx** [comment]
i think this is done apart from a few unimportant bugfixes that will come later.
